name: Deploy Netflix Clone

on:
  push:
    branches:
      - master  # Matches your current branch name

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24 # Updated to match Vercel/Modern standards

      - name: Install & Build
        run: |
          npm install
          npm run build
        env:
          # This flag tells React to ignore warnings during the build
          CI: false 
          REACT_APP_TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Your logs showed 'react-scripts build', so the folder is 'build'
          path: './build' 

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4